// ignore_for_file: unnecessary_cast

class CharactersASOIAF {
  List<Map<String, dynamic>> charListAsoiaf = [
    {
      'id': 1 as int,
      'name': "Drogon",
      'subname': "",
      'src': "assets/tdf/targ/drogon.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/drogonRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/drogonVerso.jpg" as String,
    },
    {
      'id': 2 as int,
      'name': "Viserion",
      'subname': "",
      'src': "assets/tdf/targ/viserion.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/viserionRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/viserionVerso.jpg" as String,
    },
    {
      'id': 3 as int,
      'name': "Raeghal",
      'subname': "",
      'src': "assets/tdf/targ/raeghal.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/raeghalRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/raeghalVerso.jpg" as String,
    },
    {
      'id': 4 as int,
      'name': "Unsullied Swordmasters",
      'subname': "",
      'src': "assets/tdf/targ/swordmaster.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/swordRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/swordVerso.jpg" as String,
    },
    {
      'id': 5 as int,
      'name': "Unsullied Pikemen",
      'subname': "",
      'src': "assets/tdf/targ/pikemen.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/pikemenRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/pikemenVerso.jpg" as String,
    },
    {
      'id': 6 as int,
      'name': "Stormcrow Mercenaries",
      'subname': "",
      'src': "assets/tdf/targ/mercenaries.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/mercenariesRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/mercenariesVerso.jpg" as String,
    },
    {
      'id': 7 as int,
      'name': "Stormcrow Archers",
      'subname': "",
      'src': "assets/tdf/targ/archers.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/archersRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/archersVerso.jpg" as String,
    },
    {
      'id': 8 as int,
      'name': "Drogo's Bloodriders",
      'subname': "",
      'src': "assets/tdf/targ/bloodriders.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/bloodRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/bloodVerso.jpg" as String,
    },
    {
      'id': 9 as int,
      'name': "Dothraki Screamers",
      'subname': "",
      'src': "assets/tdf/targ/screamer.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/screamerRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/screamerVerso.jpg" as String,
    },
    {
      'id': 10 as int,
      'name': "Dothraki Hrakkars",
      'subname': "",
      'src': "assets/tdf/targ/hrakkars.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/bloodRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/bloodVerso.jpg" as String,
    },
    {
      'id': 11 as int,
      'name': "Jorah",
      'subname': "THE WANDERING KNIGHT",
      'src': "assets/tdf/targ/jorah.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/jorahRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/jorahVerso.jpg" as String,
    },
    {
      'id': 12 as int,
      'name': "Grey Worm",
      'subname': "UNSULLIED COMMANDER",
      'src': "assets/tdf/targ/greyworm.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/greywRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/greywVerso.jpg" as String,
    },
    {
      'id': 13 as int,
      'name': "Belwas",
      'subname': "THE STRONG",
      'src': "assets/tdf/targ/belwas.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/belwasRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/belwasVerso.jpg" as String,
    },
    {
      'id': 14 as int,
      'name': "Barristan Selmy",
      'subname': "THE BOLD",
      'src': "assets/tdf/targ/selmy.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/selmyRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/selmyVerso.jpg" as String,
    },
    {
      'id': 15 as int,
      'name': "Xaro Xhoan Daxos",
      'subname': "MERCHANT PRINCE OF QARTH",
      'src': "assets/tdf/targ/xaro.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/xaroRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/xaroVerso.jpg" as String,
    },
    {
      'id': 16 as int,
      'name': "Illyrio Mopatis",
      'subname': "MAGISTER OF PENTOS",
      'src': "assets/tdf/targ/jorah.png" as String,
      'cardRecto': "assets/tdf/cards/Targaryen/illyrioRecto.jpg" as String,
      'cardVerso': "assets/tdf/cards/Targaryen/illyrioVerso.jpg" as String,
    },
  ];
}
